[package]
name = "ale-gui"
version = "0.3.0"
edition = "2021"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
ale-core = { path = "../ale-core" }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
uuid = { version = "1", features = ["v4"] }

[target.'cfg(target_os = "android")'.dependencies]
jni = "0.21"
ndk = { version = "0.9", features = ["media", "nativewindow", "api-level-26"] }
ndk-sys = { version = "0.6", features = ["media", "nativewindow"] }
oboe = "0.6"
quircs = "0.10.3"
slint = { version = "1.16", features = ["backend-android-activity-06"] }

[build-dependencies]
slint-build = "1.16"

[package.metadata.android]
package = "com.alemyeyes"
build_targets = ["aarch64-linux-android"]

[package.metadata.android.sdk]
min_sdk_version = 26
target_sdk_version = 34

[package.metadata.android.application]
label = "Ale, My Eyes!"
theme = "@android:style/Theme.Material.Light.NoActionBar"

[package.metadata.android.application.activity]
resizeable_activity = true
config_changes = "orientation|keyboardHidden|screenSize|screenLayout|smallestScreenSize|density|uiMode"

[[package.metadata.android.uses_permission]]
name = "android.permission.INTERNET"

[[package.metadata.android.uses_permission]]
name = "android.permission.RECORD_AUDIO"

[[package.metadata.android.uses_permission]]
name = "android.permission.MODIFY_AUDIO_SETTINGS"

[[package.metadata.android.uses_permission]]
name = "android.permission.CAMERA"
